### ISSUE TITLE
How to use it

### ISSUE THREAD

**Issue by ezsky** [profissa/yii2-state-machine#2]
I've been working on state transitions recently.
I'm very interested in the idea of this code, but I don't know how to use it.
Thank you.

**Comment by andremetzen** [comment]
hey @engylemure, can you help me here providing the installation instructions and examples of usage on a README.md?

**Comment by engylemure** [comment]
@ezsky added a small documentation of installation and usage into the [README](https://github.com/conceptho/yii2-state-machine/blob/master/README.md).

**Comment by andremetzen** [comment]
thank you @engylemure

**Comment by ezsky** [comment]
Good job thx @engylemure
